// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Light.proto

package org.DS.garyproject.SmartBuildingGRPC;

public interface booleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.booleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
