// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Light.proto

package org.DS.garyproject.SmartBuildingGRPC;

public interface lightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.lightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dname = 4;</code>
   */
  java.lang.String getDname();
  /**
   * <code>string dname = 4;</code>
   */
  com.google.protobuf.ByteString
      getDnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 brightness = 6;</code>
   */
  int getBrightness();
}
