// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Projector.proto

package org.DS.garyproject.SmartBuildingGRPC;

public interface projectorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.projectorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 volume = 6;</code>
   */
  int getVolume();

  /**
   * <code>int32 channel = 7;</code>
   */
  int getChannel();
}
