// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Light.proto

package org.DS.garyproject.SmartBuildingGRPC;

public interface stringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.stringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
