// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Projector.proto

package org.DS.garyproject.SmartBuildingGRPC;

public interface stringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.stringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
